#!/bin/bash

# This script copies $MAX files beginning from $START from 'data' directory to $DIR.
# Files in 'data' can be generated by calling src/generate-random-data.sh.

DIR=$1
START=$2
MAX=$3

if [ $# -lt 2 ]; then
    START=0
fi
if [ $# -lt 3 ]; then
    MAX=1
fi

. functions.sh

NSEQ=(`seq $START $MAX | sort -n | cut -f2- | tr '\n' ' '`)

copyFiles ../data $DIR 0
